[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#00AB41"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[server.pageConfig]
hidePage = ["main", "auth"]